### ISSUE TITLE
Featured posts are not listed

### ISSUE THREAD

**Issue by ventoux84** [pmoreno-rodriguez/grav-theme-mundana#7]
The title of the "Featured" section is displayed, but the articles are not listed.

All settings appear to be correct.
In the theme: show featured posts, featured posts category and number of featured posts to show.

In blog-config: show featured posts

In the blog post: assigned to the category declared in the theme parameters.

**Comment by pmoreno-rodriguez** [comment]
@ventoux84 

Well, the problem is that you are defining the "featured" category instead of the tag. The Mundana theme filters featured articles by tag, not category.

In partials/sidebar/featured you can see the related code:
```
  {% for p in page.evaluate({'@taxonomy.tag':featuredposts_tag}).order('date', 'desc').slice(0,featuredposts_number) %}
```
The problem is that in the theme settings, "Featured posts category" appears in the featured posts config, instead of "Featured posts tag". I should fix this in the next version.

Try using the tags from your taxonomy for featured posts.

**Comment by ventoux84** [comment]
OK, featured is relative to tags and no to categories.

But "featured" seems to bee hard coded too ! The only one tag that works is "featured" and nothing else.

**Comment by pmoreno-rodriguez** [comment]
@ventoux84 , the featured tag is not hard coded, you have an option in theme configuration to set this:

In base.html.twig:
```
{% set featuredposts_tag = theme_var('featuredposts_tag')|defined('featured') %}
```
The problem is in theme configuration, this variable is named as `featuredposts_category` instead `featuredposts_tag`. 

I need to change this issue in theme configuration for next version

**Comment by ventoux84** [comment]
Yes, but nothing else than "featured" works.

I've entered the French word "favoris" in this variable in theme config.
Then I assigned this tag to an article by also creating the tag.
Nothing is displayed in the sidebar under the title "Featured".

If I add the "featured" tag to the same article, it's displayed in the sidebar under the "Featured" title.

**Comment by pmoreno-rodriguez** [comment]
@ventoux84 Can you try the [featuredposts branch](https://github.com/pmoreno-rodriguez/grav-theme-mundana/tree/featuredposts) to see if featured posts now appear in sidebar

**Comment by ventoux84** [comment]
OK,I'll do it tomorrow; mañana, por la mañana.

**Comment by ventoux84** [comment]
I tested the [featuredposts branch](https://github.com/pmoreno-rodriguez/grav-theme-mundana/tree/featuredposts) and i saw that featured posts now appear in sidebar.
Thanks, it's perfect.
